#pragma config(Sensor, dgtl1,  limit,          sensorTouch)
#pragma config(Sensor, dgtl2,  bumper,         sensorTouch)
#pragma config(Sensor, dgtl12, red,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Labryninth challenge
  Team Members:
  Date:
  Section:


  Task Description: Get vehicle from start to finish


  Pseudocode:
  Move forward
  Wait 5
  Stop

  Turn left
  Wait 3
  Stop

  Move forward
  Wait 6
  Stop

	Turn right
	Wait 3
	Stop

	Move forward
	Wait 5
	Stop

	Turn right
	Wait 3
	Stop

	Move forward
	Wait 8
	Stop
*/

task main()
{                                     //Program begins, insert code within curly braces
	// Wait for button press
	untilTouch(bumper);

	// Move forward
	startMotor(rightMotor, 50);
	startMotor(leftMotor, 50);
	wait(4);
	stopMotor(rightMotor);
	stopMotor(leftMotor);
	wait(0.5);

	// Turn left
	startMotor(rightMotor, 100);
	startMotor(leftMotor, -50);
	wait(8);
	stopMotor(rightMotor);
	stopMotor(leftMotor);
	wait(0.5);

	// Move forward
	startMotor(rightMotor);
	startMotor(leftMotor);
	wait(6);
	stopMotor(rightMotor);
	stopMotor(leftMotor);
	wait(0.5);

	//Turn right
	startMotor(leftMotor, 100);
	startMotor(rightMotor, -50);
	wait(8);
	stopMotor(leftMotor);
	stopMotor(rightMotor);
	wait(0.5);

	// Move forward
	startMotor(rightMotor, 50);
	startMotor(leftMotor, 50);
	wait(5);
	stopMotor(rightMotor);
	stopMotor(leftMotor);
	wait(0.5);

	//Turn right
	startMotor(leftMotor, 100);
	startMotor(rightMotor, -50);
	wait(8);
	stopMotor(leftMotor);
	stopMotor(rightMotor);
	wait(0.5);

	//Move forward
	startMotor(rightMotor, 50);
	startMotor(leftMotor, 50);
	wait(8);
	stopMotor(rightMotor);
	stopMotor(leftMotor);
	wait(0.5);

}
