#pragma config(Sensor, in1,    lineTracker,    sensorLineFollower)
#pragma config(Sensor, dgtl11, green,          sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, bumper,         sensorTouch)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           rightMotor,    tmotorVex393_MC29, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Line tracker
  Team Members: Matthew Finerty
  Date: November 16th, 2016
  Section: Period 4


  Task Description: Use the bumper switch to turn on the motors, then the line tracker/follower
  to detect light/darkness to turn off motors


  Pseudocode:
  Wait until bumper switch
  Start both motors
  Wait until light
  Turn both motors off


*/

task main()
{                                     //Program begins, insert code within curly braces
	untilTouch(bumper);
	startMotor(leftMotor, 50);
	startMotor(rightMotor, 50);
	untilLight(1000, lineTracker);
	stopMotor(leftMotor);
	stopMotor(rightMotor);
}
