#pragma config(Sensor, in1,    pmeter,         sensorPotentiometer)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:
  Team Members: Matthew F
  Date:
  Section:


  Task Description: Use the potentiometer to measure the rotational shaft


  Pseudocode:
  Turn pmeter
  Turn on both motors
  Wait 3 seconds
  Stop both motors

*/

task main()
{                                     //Program begins, insert code within curly braces
	untilPotentiometerGreaterThan(2000, pmeter);
	startMotor(leftMotor, 50);
	startMotor(rightMotor, 50);
  wait(3);
  stopMotor(leftMotor);
  stopMotor(rightMotor);
}
