#pragma config(Sensor, dgtl1,  limit,          sensorTouch)
#pragma config(Sensor, dgtl2,  bumper,         sensorTouch)
#pragma config(Sensor, dgtl10, red,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, yellow,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, driveRight)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
  Project Title: Problem #2
  Team Members: Matthew Finerty
  Date:
  Section:


  Task Description:


  Pseudocode:
  Turn left motor ON
  Wait until touch bumper
  Turn left motor OFF
  Turn right motor ON
 	Wait until touch limit
 	Turn right motor OFF
 	RAINBOW!
 	Wait until bumper press
 	Turn off LEDs
 	End program

*/

task main()
{                                     //Program begins, insert code within curly braces
	startMotor(leftMotor, 50);
	untilTouch(bumper);
	stopMotor(leftMotor);
	startMotor(rightMotor, 50);
	untilTouch(limit);
	stopMotor(rightMotor);
	while (SensorValue(bumper) ==0)
	{
		turnLEDOn(green);
		wait(0.1);
		turnLEDOff(green);

		turnLEDOn(yellow);
		wait(0.1);
		turnLEDOff(yellow);

		turnLEDOn(red);
		wait(0.1);
		turnLEDOff(red);
	}
	turnLEDOff(green);
	turnLEDOff(yellow);
	turnLEDOff(red);


}
