#pragma config(Sensor, dgtl1,  limit,          sensorTouch)
#pragma config(Sensor, dgtl2,  bumper,         sensorTouch)
#pragma config(Sensor, dgtl10, red,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, yellow,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: Touch sensors
Team Members: Matthew Finerty
Date: November 9th 2016
Section: Period 4


Task Description: Use the bumper and limit switch to turn the motors on and off


Pseudocode:
-Turn left motor ON
-Press bumper switch
-Turn left motor OFF

*/

task main()
{                                     //Program begins, insert code within curly braces
	startMotor(leftMotor, 50);
	untilTouch(bumper);
	stopMotor(leftMotor);

}
